Feature/win lose conditions
g-claudino/UnrealDemo pull request #2
Opened 2024-03-06 02:27 UTC by lucas1131

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Refactor GridPawn and derivative classes to have a shared CommonGridPawn (blueprint) for shared components and event logic, like HealthBar and `OnDamageTaken` (inheritance now follows GridPawn.cpp -> CommonGridPawn (blueprint) -> specific pawn like PlayerPawn or EnemyAPawn etc. (blueprint);
Implement grayscale healthbar so each pawn can just paint with their own colors independently;
Implement win/lose conditions when all enemies or the player dies.

Fixes # (issue)
NA

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-03-07 23:12 UTC, g-claudino commented on Source/AmebamanBattleNetjob/BattleManager.h
> +	UPROPERTY(EditDefaultsOnly, Category="Player")
Revert to EditAnywhere

2024-03-07 23:14 UTC, g-claudino commented on Source/AmebamanBattleNetjob/BattleManager.cpp
> +		}
```suggestion

```

2024-03-07 23:15 UTC, g-claudino commented on Source/AmebamanBattleNetjob/BattleManager.h
> +	UPROPERTY(EditDefaultsOnly, Category="Enemies")
Revert to EditAnywhere

2024-03-07 23:16 UTC, g-claudino commented on Source/AmebamanBattleNetjob/Grid.cpp
> +	return GridPawnMap.Find(pawn->GetName()) != nullptr;
Use is valid

2024-03-07 23:20 UTC, g-claudino requested changes
Great bro, just fix a few things as they're in the specific comments

2024-03-07 23:54 UTC, lucas1131 commented on Source/AmebamanBattleNetjob/Grid.cpp
> +	return GridPawnMap.Find(pawn->GetName()) != nullptr;
In this case we are returning a `struct` and not a `UObject` so we cant use `IsValid`. Also, find returns explicitly `nullptr` if key was not found in the map.

2024-03-08 00:09 UTC, g-claudino approved these changes
Bom demais

2024-03-08 00:09 UTC, merged